# parameters.toml
file_path_in = "path/to/your/file.spm"
root_out = null
verbose = true
show_plots = true
save = true

[seg_params]
mode = "max"
[seg_params."cut seg [%]"]
start = 5
end = 5
seg_params.filter = false
seg_params."filter ord" = 10

[fit_params]
fit pha = false
detect peak = false
sens peak detect = 1.5
