# parameters.toml
dir_path_in = "path/to/your/directory/properties"
dir_path_out = null
verbose = true
show_plots = true
save = false

[user_pars]
interp fact = 3
interp func = "linear"
revert mask = false

[ref]
mode = "off"
prop = "charac tot fit: R_2 hyst"
fmt = ".5f"
min val = 0.95
max val = null
interactive = false

[[user_pars.ind maps]]
0 = ["off", "charac tot fit: area"]
1 = ["off", "fit pars: ampli_0"]
[[user_pars.ind maps]]
0 = ["on", "charac tot fit: area"]
1 = ["on", "fit pars: ampli_0"]
