# parameters.toml
dir_path_in = "path/to/your/directory/properties"
dir_path_out = null
show_plots = true
save = false

[user_pars]
mask = null
revert mask = false

[[user_pars.ind maps]]
0 = ["off", "charac tot fit: area"]
1 = ["off", "fit pars: ampli_0"]
[[user_pars.ind maps]]
0 = ["on", "charac tot fit: area"]
1 = ["on", "fit pars: ampli_0"]
